In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive

# Connecting Google Drive
drive.mount('/content/drive')

# file path to googel drive
file_path = '/content/drive/MyDrive/Netflix/all-weeks-global.xlsx'

Mounted at /content/drive

In [ ]:
# reading the raw file
rawtop10 = pd.read_excel(file_path)
rawtop10.head()

/usr/local/lib/python3.13/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,week,category,weekly_rank,show_title,season_title,weekly_hours_viewed,runtime,weekly_views,cumulative_weeks_in_top_10
0,2026-08-16,Films (English),1,The Last House,NaN,62500000,1.8667,33500000.0,2
1,2026-08-16,Films (English),2,Don't Say Good Luck,NaN,12800000,1.5833,8100000.0,1
2,2026-08-16,Films (English),3,Extinction,NaN,14000000,1.8833,7400000.0,1
3,2026-08-16,Films (English),4,72 HOURS,NaN,10500000,1.7500,6000000.0,4
4,2026-08-16,Films (English),5,Charlie and the Chocolate Factory,NaN,8300000,1.9167,4300000.0,1

In [ ]:
# dropping duplicates
top10 = rawtop10.drop_duplicates()

# converting to datetime for time-based extraction
top10['week'] = pd.to_datetime(top10['week'])

#removes record after 2025
top10 = top10[top10['week'].dt.year < 2026]

# extracting year and month components for later use
top10["year"] = top10["week"].dt.year
top10["month"] = top10["week"].dt.month

In [ ]:
top10

,week,category,weekly_rank,show_title,season_title,weekly_hours_viewed,runtime,weekly_views,cumulative_weeks_in_top_10,year,month
1320,2025-12-28,Films (English),1,Dr. Seuss' The Grinch,NaN,23700000,1.4333,16500000.0,14,2025,12
1321,2025-12-28,Films (English),2,Wake Up Dead Man: A Knives Out Mystery,NaN,28700000,2.4333,11800000.0,3,2025,12
1322,2025-12-28,Films (English),3,KPop Demon Hunters,NaN,15100000,1.6667,9100000.0,28,2025,12
1323,2025-12-28,Films (English),4,How the Grinch Stole Christmas,NaN,13300000,1.7333,7700000.0,8,2025,12
1324,2025-12-28,Films (English),5,Goodbye June,NaN,13600000,1.9333,7000000.0,1,2025,12
...,...,...,...,...,...,...,...,...,...,...,...
10715,2021-07-04,TV (Non-English),6,Elite,Elite: Season 1,10530000,NaN,NaN,1,2021,7
10716,2021-07-04,TV (Non-English),7,Elite,Elite: Season 3,10200000,NaN,NaN,1,2021,7
10717,2021-07-04,TV (Non-English),8,Elite,Elite: Season 2,10140000,NaN,NaN,1,2021,7
10718,2021-07-04,TV (Non-English),9,Katla,Katla: Season 1,9190000,NaN,NaN,1,2021,7
10719,2021-07-04,TV (Non-English),10,Record of Ragnarok,Record of Ragnarok: Season 1,9140000,NaN,NaN,1,2021,7

In [ ]:
# checking datatypes for show titles
top10["show_title"].map(type).value_counts()

show_title
<class 'str'>    9400
Name: count, dtype: int64

In [ ]:
# checking data types for season titles
# (floats are ok because of the missing values)
top10["season_title"].map(type).value_counts()

season_title
<class 'float'>    4838
<class 'str'>      4562
Name: count, dtype: int64

In [ ]:
# uploading to google drive
file_path = '/content/drive/MyDrive/Netflix/Top10.csv'
top10.to_csv(file_path, index=False)